### ISSUE TITLE
Uncaught ReferenceError: i is not defined

### ISSUE THREAD

**Issue by mschilder** [UndefinedOffset/silverstripe-keyboardshortcuts#10]
I've setup the latest Silverstripe with composer ("silverstripe/cms": "3.3.*", "minimum-stability": "dev", "prefer-stable": true) together with a.o. fluent ("tractorcow/silverstripe-fluent": "*") and keyboardshortcuts ("UndefinedOffset/silverstripe-keyboardshortcuts": "*").

Now when changing the Fluent language in the CMS the CMS breaks because of this error: Uncaught ReferenceError: i is not defined. When removing line 209 from KeyboardShortcuts.js, the problem is solved: 

//Mousetrap(this.getEditor().getInstance().contentWindow.document.body).noTinyMCEBind(listeners[i].key, listeners[i].callback, listeners[i].action);

**Comment by UndefinedOffset** [comment]
thanks for the heads up should be fixed now :)
