### ISSUE TITLE
save & publish under page-settings doesn't work

### ISSUE THREAD

**Issue by lerni** [UndefinedOffset/silverstripe-keyboardshortcuts#12]
under page-settings (/admin/pages/settings/show/1) `command+shift+s` doesn't work but `command+s` does. "Doesn't work" means it just won't save. I see this with Chrome 59 & FF 54 on osX with SS 3.6.1 and 0.3.3 of this module.

**Comment by UndefinedOffset** [comment]
thanks and fixed I'll tag a new release soon

**Comment by UndefinedOffset** [comment]
new release 0.4.0 tagged, note the change in #13

**Comment by lerni** [comment]
@UndefinedOffset wow that was fast - appreciate it very much! Works perfectly now!
