### ISSUE TITLE
shift+n creates a new Page

### ISSUE THREAD

**Issue by lerni** [UndefinedOffset/silverstripe-keyboardshortcuts#14]
shift+n creates a new Page so one cannot type "N" in any field. related to https://github.com/UndefinedOffset/silverstripe-keyboardshortcuts/issues/13

**Comment by UndefinedOffset** [comment]
Oops I'll do a bug fix in a bit, guess I'll need a new one idea ;)

**Comment by UndefinedOffset** [comment]
I might do ctrl/command + alt + n instead, need to test first

**Comment by UndefinedOffset** [comment]
ok my dumb moment is now fixed ;) use release 0.4.1 or master
